---
    version: "3.8"
    services:
        plex:
            image: linuxserver/plex
            network_mode: host
            environment: 
                - PUID=1000
                - PGID=1000
                - VERSION=docker
            volumes:
                - /home/ubuntu/dockerScale/plex/config
                - /home/ubuntu/dockerScale/plex/movies
